name:                fingerd
version:             0.1.0.0
github:              "fcracker79/fingerd"
license:             BSD3
author:              "Mirko Bonasorte"
maintainer:          "mirko@mirko.io"
copyright:           "2021 Mirko Bonasorte"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fcracker79/fingerd#readme>

dependencies:
- aeson 
- async
- attoparsec
- base >= 4.7 && < 5
- bytestring
- containers 
- exceptions
- managed 
- monad-loops 
- mtl 
- network
- random 
- raw-strings-qq
- resource-pool
- sqlite-simple
- text 
- text-format-simple
- threads
- transformers 
- unordered-containers
- vector
- mmorph

library:
  source-dirs: src

executables:
  fingerd:
    main:                src/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - fingerd

tests:
  unit:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HUnit
      - test-framework
      - test-framework-hunit
      - hspec
      - programminghaskell

  integration:
    main: Spec.hs
    source-dirs: test/integration
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HUnit
      - test-framework
      - test-framework-hunit
      - hspec
      - fingerd
      - threads

default-extensions:
  - TypeSynonymInstances
  - FlexibleInstances
  - MonadComprehensions
  - FlexibleContexts
  - RankNTypes
  - TypeOperators
  - UndecidableInstances
  - MultiParamTypeClasses
  - FunctionalDependencies
  - OverloadedStrings
  - LambdaCase
  - TupleSections
